### ISSUE TITLE
[UI] Flutter web: Recently updated carousel slider

### ISSUE THREAD

**Issue by Harrisonnguyen1210** [CoderPush/Stepper#100]
### What
Recently updated area section needs a different UI for Flutter web

![image](https://user-images.githubusercontent.com/33485572/142818576-08204103-486e-42e6-b606-d40cee27d060.png)

### How
- [x] New UI design for flutter web, eg: carousel slider
- [x] Implement new UI

**Comment by conghua2411** [comment]
update UI in PR: https://github.com/CoderPush/Stepper/pull/191
